


DESC team;

SELECT * FROM schedule;

SELECT * FROM stadium;

SELECT * FROM team;

SELECT * FROM player;


ALTER TABLE TEAMZ
RENAME TO PROJECT_TEAM;
ALTER TABLE TEAMW
RENAME TO MEMBER;

SELECT *FROM MEMBER



CREATE TABLE SUBJECT
(
    SUB_SEQ      DECIMAL PRIMARY KEY,
    SUB_NAME  VARCHAR2 (20)
);

ALTER TABLE RECODE
  ADD RECORD_SEQ	DECIMAL PRIMARY KEY;
  
  ALTER TABLE RECODE
  ADD   GRADE      VARCHAR2 (20);
  



ALTER TABLE RECODE DROP (RECORD_SEQ)  ;
                    -- 칼럼 자체를 지울때





INSERT INTO SUBJECT
     VALUES ('1', 'JAVA');
     
INSERT INTO SUBJECT
     VALUES ('2', 'SQL');
     
INSERT INTO SUBJECT
     VALUES ('3', 'HTML5');
     
INSERT INTO SUBJECT
     VALUES ('4', 'PYTHON');

CREATE TABLE EXAM
(
    EXAM_ID      DECIMAL PRIMARY KEY,
    MONTH     VARCHAR2 (20),
    SCORE DECIMAL,
    MEM_ID DECIMAL,
    SUB_SEQ DECIMAL,
    RECORD_SEQ DECIMAL


);

CREATE TABLE SUBJECT
(
   SUB_SEQ    DECIMAL PRIMARY KEY,
    SUB_NAME    VARCHAR2 (20)
);

CREATE TABLE RECORD
(
   RECORD_SEQ DECIMAL PRIMARY KEY,
   GRADE    VARCHAR2 (20), 
    AVG    DECIMAL
);


INSERT INTO SUBJECT
     VALUES ('1', 'JAVA');
     
INSERT INTO SUBJECT
     VALUES ('2', 'SQL');
     
INSERT INTO SUBJECT
     VALUES ('3', 'HTML5');
     
INSERT INTO SUBJECT
     VALUES ('4', 'PYTHON');
     INSERT INTO SUBJECT
     VALUES ('5', 'R');
     

    
                    
ALTER TABLE MEMBER 
RENAME COLUMN MEM_AGE TO AGE;

ALTER TABLE SUBJECT
MODIFY (SUB_SEQ  PRIMARY KEY); 


DROP TABLE RECODE;


  ALTER TABLE SUBJECT
  ADD   SUB_SEQ      DECIMAL;
  


ALTER TABLE MEMBER
    ADD CONSTRAINT MEMBER_FK FOREIGN KEY (TEAM_ID) REFERENCES PROJECT_TEAM (TEAM_ID);
    
    

select*from information_schema.table_constraints where table_name=EXAM;




   


ALTER TABLE EXAM ADD CONSTRAINT EXAM_FK_MEMBER_ID FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID);
ALTER TABLE EXAM ADD CONSTRAINT EXAM_FK_SUB_SEQ FOREIGN KEY (SUB_SEQ) REFERENCES SUBJECT (SUB_SEQ);  
  ALTER TABLE EXAM ADD CONSTRAINT EXAM_FK_RECORD_SEQ FOREIGN KEY (RECORD_SEQ) REFERENCES RECORD (RECORD_SEQ); 
    
    SELECT *FROM RECORD;
    
    DESC subject;
    
    
    SELECT *from TAB
    